### ISSUE TITLE
Crashes on launch due to space in mod ID of "mod sets_common_config_"

### ISSUE THREAD

**Issue by Poopooracoocoo** [SettingDust/ModSets#12]
The issue occurs with both _mod_sets-ingame-1.7.0+sha.37ee792+1.20.1.jar_ (mod sets_common_config_) and _mod_sets-config-1.7.0+sha.37ee792+1.20.1.jar_ (mod sets_common_ingame_)

Mod Sets was downloaded from Modrinth: https://modrinth.com/mod/mod-sets/version/1.7.0-intermediary

[latest.log](https://github.com/SettingDust/ModSets/files/15031495/latest.log)

<details><summary>Details</summary>

```
[09:51:15] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.10
[09:51:15] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:197) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:159) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:159) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.10.jar:?]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\anon\AppData\Roaming\PrismLauncher\instances\test\.minecraft\mods\mod_sets-intermediary-1.7.0+sha.37ee792+1.20.1.jar]: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at C:\Users\anon\AppData\Roaming\PrismLauncher\instances\test\.minecraft\mods\mod_sets-intermediary-1.7.0+sha.37ee792+1.20.1.jar -> META-INF/jars/mod_sets-config-1.7.0+sha.37ee792+1.20.1.jar: Invalid mod id mod sets_common_config_: It contains invalid characters: ' '!
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:156) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.10.jar:?]
	... 6 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\anon\AppData\Roaming\PrismLauncher\instances\test\.minecraft\mods\mod_sets-intermediary-1.7.0+sha.37ee792+1.20.1.jar]: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at C:\Users\anon\AppData\Roaming\PrismLauncher\instances\test\.minecraft\mods\mod_sets-intermediary-1.7.0+sha.37ee792+1.20.1.jar -> META-INF/jars/mod_sets-config-1.7.0+sha.37ee792+1.20.1.jar: Invalid mod id mod sets_common_config_: It contains invalid characters: ' '!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:300) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:249) ~[fabric-loader-0.15.10.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at C:\Users\anon\AppData\Roaming\PrismLauncher\instances\test\.minecraft\mods\mod_sets-intermediary-1.7.0+sha.37ee792+1.20.1.jar -> META-INF/jars/mod_sets-config-1.7.0+sha.37ee792+1.20.1.jar: Invalid mod id mod sets_common_config_: It contains invalid characters: ' '!
	at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:249) ~[fabric-loader-0.15.10.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeNestedMods(ModDiscoverer.java:500) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:342) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:290) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:249) ~[fabric-loader-0.15.10.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at C:\Users\anon\AppData\Roaming\PrismLauncher\instances\test\.minecraft\mods\mod_sets-intermediary-1.7.0+sha.37ee792+1.20.1.jar -> META-INF/jars/mod_sets-config-1.7.0+sha.37ee792+1.20.1.jar: Invalid mod id mod sets_common_config_: It contains invalid characters: ' '!
	at net.fabricmc.loader.impl.metadata.MetadataVerifier.checkModId(MetadataVerifier.java:146) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.metadata.MetadataVerifier.verify(MetadataVerifier.java:52) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.parseMetadata(ModMetadataParser.java:49) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.parseMetadata(ModDiscoverer.java:506) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarStream(ModDiscoverer.java:396) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:276) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:249) ~[fabric-loader-0.15.10.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeNestedMods(ModDiscoverer.java:500) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:342) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:290) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:249) ~[fabric-loader-0.15.10.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
``` 

</details>

**Comment by Poopooracoocoo** [comment]
I confirm that Mod Sets 1.7.1 no longer causes a crash on launch! Thanks!
