### ISSUE TITLE
[Minecraft 1.20.1] Minecraft Crashes when mod ("Mod Sets") is added

### ISSUE THREAD

**Issue by Rayregula** [SettingDust/ModSets#19]
## **Description:**
Minecraft immediately fails on start when adding the Mod Sets mod, seems fine with just the dependencies:

## Crash log:

<details>
  <summary>Crash Log</summary>
  
```
[01:31:30] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.9
[01:31:31] [main/INFO]: Loading 88 mods:
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.12.3+kotlin.2.0.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- java 22
	- kinecraft_serialization_container 1.16.0
	   \-- kinecraft_serialization 1.16.0
	- minecraft 1.20.1
	- mod_sets 1.10.1
	   |-- preloading_tricks 1.2.3
	   |    \-- preloading_tricks_language_adapter 1.2.3
	   |-- settingdust_modsets_common 1.10.1
	   \-- settingdust_modsets_ingame 1.10.1
	- modmenu 7.2.2
	- yet_another_config_lib_v3 3.6.1+1.20.1-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
[01:31:31] [main/WARN]: [PreloadingTricks/LanguageAdapter] Errors when loading preloading tricks may be intended since the implementations may targeting multiple mod loaders
[01:31:31] [main/INFO]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.fabric.FabricLanguageProviderCallback
[01:31:31] [main/INFO]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.quilt.QuiltLanguageProviderCallback
[01:31:31] [main/ERROR]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.quilt.QuiltLanguageProviderCallback failed: java.lang.ClassNotFoundException: org.quiltmc.loader.impl.QuiltLoaderImpl
[01:31:31] [main/INFO]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.neoforge.fml.FMLLanguageProviderCallback
[01:31:31] [main/ERROR]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.neoforge.fml.FMLLanguageProviderCallback failed: java.lang.ClassNotFoundException: net.neoforged.fml.loading.FMLLoader
[01:31:31] [main/INFO]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.forge.fml.FMLLanguageProviderCallback
[01:31:31] [main/ERROR]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.forge.fml.FMLLanguageProviderCallback failed: java.lang.ClassNotFoundException: net.minecraftforge.fml.loading.FMLLoader
[01:31:31] [main/INFO]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.forge.fml40.FML40LanguageProviderCallback
[01:31:31] [main/ERROR]: [PreloadingTricks/LanguageAdapter] Loading settingdust.preloadingtricks.forge.fml40.FML40LanguageProviderCallback failed: java.lang.ClassNotFoundException: net.minecraftforge.fml.loading.FMLLoader
[01:31:31] [main/INFO]: [PreloadingTricks/ModSetup] Loading settingdust.modsets.fabric.FabricSetupModCallback
[01:31:31] [main/INFO]: Loading mods from 0 sub folders in mods
[01:31:31] [main/INFO]: Loading 0 additional mods:
[01:31:31] [main/INFO]: [PreloadingTricks/ModSetup] Loading settingdust.modsets.quilt.QuiltSetupModCallback
[01:31:31] [main/ERROR]: [PreloadingTricks/ModSetup] Loading settingdust.modsets.quilt.QuiltSetupModCallback failed: java.lang.ClassNotFoundException: org.quiltmc.loader.api.plugin.ModContainerExt
[01:31:31] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/Jason%20Regula/Documents/MultiMC/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[01:31:31] [main/INFO]: Compatibility level set to JAVA_16
[01:31:31] [main/INFO]: Compatibility level set to JAVA_17
[01:31:32] [main/ERROR]: Mixin prepare for mod kinecraft_serialization failed preparing JsonImplMixin in kinecraft_serialization.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: kinecraft_serialization.mixins.json:JsonImplMixin from mod kinecraft_serialization target kotlinx.serialization.json.JsonImpl was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: kinecraft_serialization.mixins.json:JsonImplMixin from mod kinecraft_serialization target kotlinx.serialization.json.JsonImpl was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:947) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:881) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:933) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:858) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Failed to start Minecraft:
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [kinecraft_serialization.mixins.json:JsonImplMixin from mod kinecraft_serialization] from phase [DEFAULT] in config [kinecraft_serialization.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: kinecraft_serialization.mixins.json:JsonImplMixin from mod kinecraft_serialization target kotlinx.serialization.json.JsonImpl was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:947)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:881)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:933)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:858)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 19 more
Exiting with -1
```
</details>

[https://paste.ee/p/M8ObR](https://paste.ee/p/M8ObR)

Mentions:
`Critical problem: kinecraft_serialization.mixins.json:JsonImplMixin from mod kinecraft_serialization target kotlinx.serialization.json.JsonImpl was loaded too early.`

Which makes it sound like the other mod is at fault but without Mod Sets there is no crashing and I don't know another mod that uses Kinecraft to test with. So figured it was best to make the issue under the mod I want to use.

I'm unsure if there are version requirements I'm unaware of or another mod that is missing?

I expect it is just a mistake on my part.

## Information

**The only mods active are the following:**

- Minecraft 1.20.1
- Fabric Loader 0.16.9 (tried 0.16.2 as well)

- Fabric-Api 0.92.2
- Fabric Language Kotlin 1.12.3
- Kinecraft Serialization 1.16.0 -- (tried 1.15.0 as well)
- Mod Sets 1.10.1
- Modmenu 7.2.2 -- (same issue without)
- Yet Another Config Lib 3.6.1

## **To Reproduce:**

1. Install Mod Sets and its dependencies (as above)
2. Launch the game
3. See Crash

Doing the below, everything seems fine (other then the mod not being active)

1. Remove Mod Sets
2. Launch Game
3. Game starts fine

**Comment by Rayregula** [comment]
Edited for clarity

**Comment by SettingDust** [comment]
Well. `kinecraft_serialization` has some problem. I need to refactor it. I'll publish a version with workaround before refactor.

**Comment by Rayregula** [comment]
I'll give it a try once it finishes building! didn't expect such a quick response and at 2am

**Comment by Rayregula** [comment]
> Fixed another problem https://github.com/SettingDust/kinecraft-serialization/actions/runs/11772942462/job/32789075166

Rip
![image](https://github.com/user-attachments/assets/45bd05f5-5b6d-4134-b6f0-be9390e69f49)

**Comment by SettingDust** [comment]
Both the Mod Sets and Kinecraft Serialization updated. Should be fixed

**Comment by Rayregula** [comment]
> Both the Mod Sets and Kinecraft Serialization updated. Should be fixed

Thanks! I'll give it a try tomorrow.

**Comment by Rayregula** [comment]
> > Both the Mod Sets and Kinecraft Serialization updated. Should be fixed
> 
> Thanks! I'll give it a try tomorrow. (it's now 3:00 in the morning and I need sleep)

Nevermind.
I gave it a try anyway, and Minecraft opened without issue. I'll be able to do more with it tomorrow though.

Thank you.
