### ISSUE TITLE
rule file isn't being read

### ISSUE THREAD

**Issue by thimblebird** [SettingDust/ModSets#21]
from the log:
```
[17:50:01] [Render thread/ERROR]: Failed to load rule almost_vanilla.json
kotlinx.serialization.SerializationException: Serializer for class 'JsonElement' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.

	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:90) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.7.3-4423b6342820c733.jar:?]
	at kotlinx.serialization.SerializersKt__SerializersKt.noCompiledSerializer(Serializers.kt:387) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.7.3-4423b6342820c733.jar:?]
	at kotlinx.serialization.SerializersKt.noCompiledSerializer(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.7.3-4423b6342820c733.jar:?]
	at settingdust.kinecraft.serialization.v1_20.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.kt:23) ~[kinecraft_serialization_1_20-1.16.1-1f2144505ab5103e.jar:?]
	at settingdust.kinecraft.serialization.ComponentSerializer.deserialize(ComponentSerializer.kt:529) ~[kinecraft_serialization-1.16.1-c782230e64d6e288.jar:?]
	at settingdust.kinecraft.serialization.ComponentSerializer.deserialize(ComponentSerializer.kt:11) ~[kinecraft_serialization-1.16.1-c782230e64d6e288.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.7.3-8a3c327f51928455.jar:?]
	at kotlinx.serialization.ContextualSerializer.deserialize(ContextualSerializer.kt:67) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.7.3-4423b6342820c733.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.7.3-8a3c327f51928455.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.7.3-4423b6342820c733.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.7.3-4423b6342820c733.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.7.3-8a3c327f51928455.jar:?]
	at settingdust.modsets.ingame.RuleSet$$serializer.deserialize(Rule.kt:31) ~[settingdust_modsets_ingame-1.10.3-70dcc895ccbcd94b.jar:?]
	at settingdust.modsets.ingame.RuleSet$$serializer.deserialize(Rule.kt:31) ~[settingdust_modsets_ingame-1.10.3-70dcc895ccbcd94b.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.7.3-8a3c327f51928455.jar:?]
	at kotlinx.serialization.json.internal.JsonStreamsKt.decodeByReader(JsonStreams.kt:111) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.7.3-8a3c327f51928455.jar:?]
	at kotlinx.serialization.json.JvmStreamsKt.decodeFromStream(JvmStreams.kt:61) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.7.3-8a3c327f51928455.jar:?]
	at settingdust.modsets.ingame.ModSetsIngameConfig.reload(ModSetsIngameConfig.kt:177) ~[settingdust_modsets_ingame-1.10.3-70dcc895ccbcd94b.jar:?]
	at settingdust.modsets.ingame.ModSetsIngameConfig$reload$1.invokeSuspend(ModSetsIngameConfig.kt) ~[settingdust_modsets_ingame-1.10.3-70dcc895ccbcd94b.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-2.0.21-6301f741d3f6049d.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.9.0-91a402bc2478d6a4.jar:?]
	at settingdust.modsets.ingame.ModSetsIngameConfig.generateConfigScreen$lambda$19(ModSetsIngameConfig.kt:106) ~[settingdust_modsets_ingame-1.10.3-70dcc895ccbcd94b.jar:?]
	at dev.isxander.yacl3.dsl.APIKt.YetAnotherConfigLib(API.kt:30) ~[YetAnotherConfigLib-3.6.1+1.20.1-fabric.jar:?]
	at settingdust.modsets.ingame.ModSetsIngameConfig.generateConfigScreen(ModSetsIngameConfig.kt:104) ~[settingdust_modsets_ingame-1.10.3-70dcc895ccbcd94b.jar:?]
	at settingdust.modsets.fabric.ModSetsModMenu.getModConfigScreenFactory$lambda$0(ModSetsModMenu.kt:9) ~[mod_sets-1.10.3.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:61) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.openConfig(ModListEntry.java:120) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25402(ModListEntry.java:110) ~[modmenu-7.2.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25402(ModListWidget.java:264) ~[modmenu-7.2.2.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
```

do you need more info? not really sure what happens here, because that rule file is just the example rule basically. even with just a label it throws the same error:

![image](https://github.com/user-attachments/assets/c3087403-0b2c-43bc-a892-a7d6c9cd035a)

**Comment by thimblebird** [comment]
https://mclo.gs/1zAG6ue

config:
[modsets.zip](https://github.com/user-attachments/files/17787838/modsets.zip)

**Comment by SettingDust** [comment]
test the new version 1.10.4

**Comment by thimblebird** [comment]
![image](https://github.com/user-attachments/assets/2e499255-e81b-4f6d-8d00-d512f25086e1)

https://mclo.gs/1nthivI

same config

**Comment by thimblebird** [comment]
![image](https://github.com/user-attachments/assets/59418e1f-4330-4a24-8ec8-04b180084062)

just noticed the `modsets.json` is being read regardless of the mod menu error. otherwise these tags (from my "advanced" modsets.json) wouldn not show up 🤔 so, that bit is working :D

**Comment by SettingDust** [comment]
There are something wrong when generating yacl config screen. Will take a look some while

**Comment by thimblebird** [comment]
so close and create a new issue? don't want to prematurely close now, but the issue with this particular issue seems resolved!

**Comment by SettingDust** [comment]
Make sense. Better for anyone running into the same issue
