### ISSUE TITLE
Crashing when trying to open the config screen

### ISSUE THREAD

**Issue by craftish37** [SettingDust/ModSets#6]
Playing on Quilt 1.20.1 - 0.20.0-beta.4
ModSets version 1.2 - 1.20.1

When trying to open the config via modmenu, game crashes with [this output](https://github.com/SettingDust/ModSets/files/12216578/2023-07-31-7.log)

**Comment by SettingDust** [comment]
I can't reproduce it in development. Can your provide your config and mods?

**Comment by craftish37** [comment]
Sure, will a zip do it ?

**Comment by SettingDust** [comment]
> Sure, will a zip do it ?

ya

**Comment by SettingDust** [comment]
[mod_sets-1.2.0+1.20.1-fabric-intermediary.zip](https://github.com/SettingDust/ModSets/files/12223921/mod_sets-1.2.0%2B1.20.1-fabric-intermediary.zip)
Can you test with this first? Maybe it get fixed

**Comment by craftish37** [comment]
https://www.mediafire.com/file/rtcxcfn376rsdr6/instance.zip/file
I will test it in some hours, gotta go quickly

**Comment by SettingDust** [comment]
notice. It won't load sub fir more than depth 1. Since there is defined mod sets for complex config and you can't publish the tree to platform like CurseForge

**Comment by SettingDust** [comment]
Hm. It appears randomly. Can't reproduce stable.

**Comment by SettingDust** [comment]
> notice. It won't load sub fir more than depth 1. Since there is defined mod sets for complex config and you can't publish the tree to platform like CurseForge

Well. ModSets load sub dir on fabric and forge but not quilt. It depends on how the quilt load it.

**Comment by SettingDust** [comment]
And I reproduce the issue. Causing by there isn't any rules. I'll fix it in next version

**Comment by SettingDust** [comment]
https://modrinth.com/mod/mod-sets/version/hfdtZhTP

**Comment by craftish37** [comment]
Updated to 1.2.1, got a new issue
![image](https://github.com/SettingDust/ModSets/assets/63811617/2b5ebd68-8971-41c4-b05c-43fce095d917)

Extract from logs :

```
Error from mod 'mod_sets'
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
	at settingdust.modsets.game.Rules.getConfig(Rules.kt:171)
	at settingdust.modsets.game.Rules.createScreen(Rules.kt:162)
	at settingdust.modsets.game.ModSetsModMenu.getModConfigScreenFactory$lambda$0(ModSetsModMenu.kt:9)
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:61)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:114)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:15)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:56)
	at net.minecraft.class_339.method_25402(class_339.java:189)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_442.method_25402(class_442.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by SettingDust** [comment]
Hmmm. It's seems the old one.

**Comment by SettingDust** [comment]
> Hmmm. It's seems the old one.

No-op. It won't crash. And will be fine at second time. Need explain

**Comment by craftish37** [comment]
Well I restarted the game multiple times and still encounter this issue
As for explainations I'm not quite sure what kind of information you may need more

**Comment by SettingDust** [comment]
> Well I restarted the game multiple times and still encounter this issue As for explainations I'm not quite sure what kind of information you may need more

Just reenter the mod menu not works?

**Comment by craftish37** [comment]
Fixed, thank you so much 😄
